### PR TITLE
Adding in Hb tests

### PR DESCRIPTION
**Pull request by Jennit07**
Changes to test syntax to include a count of episodes in each health board and also the total cost for each health board

### CODE REVIEW

**Review by Moohan — CHANGES_REQUESTED** [review]
Looks good so far 👍 Could you add:

- [ ] OoHs (HB)
- [ ] Homelessness (Local Authority)
- [ ] For 17/18; social care (Local Authority)
 please?

**Comment by Jennit07** [comment]
GP OOH hb tests added, locality testing for homelessness and 1718 social care already completed. Ready to merge onto march-21-update if you are happy with the changes

**Review by Moohan — CHANGES_REQUESTED** [review]
Could you copy to all years, please?

**Comment by Jennit07** [comment]
Sure, that should be GP OOH copied to all years, previous commit has all other tests years copied over. Will merge if youre happy for me to

**Review by Moohan — APPROVED** [review]

**Pull request merged**
