### PR TITLE
Convert postcode lookup into a function for processing in phase 1b

### PR DESCRIPTION
**Pull request by Jennit07**
I've left pc lookup tests for now as the function `write_tests_xlsx` now looks for a year parameter which does not fit how this is set up - I will make a new issue to review lookup tests #406

The postcode lookup is now in one function called `process_lookup_postcode.R`

### CODE REVIEW

**Comment by lizihao-anu** [comment]
As for the issue "`write_tests_xlsx` now looks for a year parameter ", would it be ok to allow `year` to be a missing argument? We can use if else to separate the cases with or without `year`? Hope I make myself clear.

If so, can I push a commit directly to function_lookup_pc branch?

**Review by lizihao-anu — APPROVED** [review]
Happy to merge if there is no intention to fix `write_tests_xlsx.R` here

**Comment by Moohan** [comment]
> Happy to merge if there is no intention to fix `write_tests_xlsx.R` here

Dealt with in #376

**Comment by Jennit07** [comment]
Simplified the code in the tests. Ready to merge

**Pull request merged**
