### PR TITLE
Updates to Social Care and their targets

### PR DESCRIPTION
**Pull request by Moohan**
I've already split some changes out into their own PRs where they're not related to targets and are just bugs, those PRs should be checked and merged first, and then the `test-production` branch should be brought up to date.

- [x] #614 
- [x] #615 
- [x] #616 
- [x] #618 

Once those have been checked this one should be easier to review, I think all but one [(311274a)](https://github.com/Public-Health-Scotland/source-linkage-files/pull/617/commits/311274aea83dba0b4d32419ae45305e23ad9d89a) of the commits are pretty isolated so can be looked at separately.

### CODE REVIEW

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4631549057/attempts/1).

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4631633651/attempts/1).

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4635940184/attempts/1).

**Comment by Jennit07** [comment]
I get the following errors when running `targets::tar_make_future()` which i think are due to the 'raw' sc data not being available in the folder. I will test this and write these to disk to see if this helps

```
✖ error target source_sc_alarms_tele_1920
Error: could not load dependencies of target source_sc_alarms_tele_1920. file must be a "InputStream"

• start target source_sc_home_care_1920
✖ error target source_sc_home_care_1920
Error: could not load dependencies of target source_sc_home_care_1920. file must be a "InputStream"

• start target tests_alarms_telecare_1920
✖ error target tests_alarms_telecare_1920
Error: could not load dependencies of target tests_alarms_telecare_1920. file must be a "InputStream"

• start target tests_home_care_1920
✖ error target tests_home_care_1920
Error: could not load dependencies of target tests_home_care_1920. file must be a "InputStream"

✖ error target all_care_home
Error: unused arguments (sc_demog_lookup = sc_demog_lookup, slf_deaths_lookup = slf_chi_deaths_lookup, ch_name_lookup_path = slf_ch_name_lookup_path, spd_path = spd_path)

• start target source_sc_care_home_1920
✖ error target source_sc_care_home_1920
Error: could not load dependencies of target source_sc_care_home_1920. file must be a "InputStream"

• start target tests_care_home_1920
✖ error target tests_care_home_1920
Error: could not load dependencies of target tests_care_home_1920. file must be a "InputStream"


• start target all_care_home_tests
✖ error target all_care_home_tests
Error: could not load dependencies of target all_care_home_tests. file must be a "InputStream"

```

**Comment by Moohan** [comment]
Did you install the package from the new branch before running? The error about incorrect params is odd.

**Comment by Jennit07** [comment]
> Did you install the package from the new branch before running? The error about incorrect params is odd.

Installing the package looked like this corrected the errors i was getting. I was then able to run the Social Care targets within the pipeline successfully. I will approve and merge this PR

**Review by Jennit07 — APPROVED** [review]
Tested this through and social care targets are now working correctly. Will approve/merge

**Pull request merged**
