### PR TITLE
Refactor the episode file code

### PR DESCRIPTION
**Pull request by Moohan**
This is a partial WIP as I haven't fully checked/tested everything before I finished.

Some of the commits could be cherry-picked and merged into `main-R`. Changes:

- ~Fix a bug in correct_demog~ - Now in #631 
- ~Improve documentation~ / trimmed comments and commented out code - Partially committed to `main-R`
- ~Add some TODOs for potential missing bits (SPARRA / HHG?)~
- ~Extracted two new functions for bits of code~
- ~Reworked both CIJ marker functions to make the code more readable but needed testing!~
- ~Make missing CHI numbers NA. I think this makes more sense, than `""`.~

### CODE REVIEW

**Comment by Jennit07** [comment]
I've been testing this today and the ep file is still running out of memory. I think the cause is when trying to create the service use cohort, it has been failing and kicking me out of PWB. This is when selecting the max profile. I have managed to create a temp file without the cohorts matched on but still need to run tests on this/try create a final file. 

One WIP thing i have been trying is changing the outputs of the demog and service use cohorts to `write_parquet` instead of `rds` and this allowed me to create a service use file. However once this was done, the session ran out of memory and could not  use the final function for creating the ep file `fill_geographies`

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4730214287/attempts/1).

**Comment by Moohan** [comment]
Some build notes need fixing:

- [ ] `run_episode_file: no visible binding for global variable ‘.’`
- [ ] `Package listed in more than one of Depends, Imports, Suggests, Enhances:` - `arrow`
- [ ] `Argument items with no description in Rd object 'create_cost_inc_dna':` - `ep_file_data`

**Comment by Jennit07** [comment]
Checked through this and i think it is ready to merge. I mentioned in the R conversion meeting today that it was looking strange when running the `before refactor` code as the total number of obs seemed to be double. I have checked this through again, running in chunks and i dont seem to have this problem now for some reason? I have ran the tests on this again and they are matching with the output (ran with refactor code).

I will check/fix the build notes above then i think its ready to merge. I will have a look at dealing with any conflicts and let you know if i run into anything/query conflicts with you.

**Comment by Jennit07** [comment]
Outstanding build notes which should be addressed on a separate branch: 

```
❯ checking package dependencies ... NOTE
  Imports includes 33 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.
```

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-get_lookup_paths.R:25'): SPD file path returns as expected ─────
Error in `get_file_path(directory = spd_dir, file_name = file_name, ext = ext, 
    file_name_regexp = stringr::str_glue("Scottish_Postcode_Directory_.+?\\.{ext}"))`: The file 'NA' does not exist in '/conf/linkage/output/lookups/Unicode/Geography/Scottish Postcode Directory'
Backtrace:
     ▆
  1. ├─base::suppressMessages(...) at test-get_lookup_paths.R:25:2
  2. │ └─base::withCallingHandlers(...)
  3. ├─testthat::expect_equal(...) at test-get_lookup_paths.R:29:4
  4. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
  5. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  6. ├─fs::path_ext(get_spd_path(ext = "zsav"))
  7. └─createslf::get_spd_path(ext = "zsav")
  8.   └─createslf::get_file_path(directory = spd_dir, file_name = file_name, ext = ext, file_name_regexp = stringr::str_glue("Scottish_Postcode_Directory_.+?\\.{ext}"))
  9.     └─cli::cli_abort(error_text)
 10.       └─rlang::abort(...)
```

**Review by Jennit07 — APPROVED** [review]
See comment for existing build notes to be addressed separately. I've checked this and think it is now ready to merge

**Pull request merged**
