### PR TITLE
Add tests to the targets pipeline

### PR DESCRIPTION
**Pull request by Moohan**
Outstanding tasks
- [x] Create a fix for tests where there is no data in that year e.g. DN 2223

### CODE REVIEW

**Comment by Moohan** [comment]
Although the tests have mostly worked I think it would be worth amending the `write_tests` function to write a new file per year (per update). Targets writes the tests as soon as it's done which looks like a pretty random order.

**Comment by Moohan** [comment]
> @check-spelling-bot apply updates.

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/5132257424/attempts/1).

**Comment by Jennit07** [comment]
`write_tests` function now merged so tests should write out per year now

**Review by Jennit07 — APPROVED** [review]
Looks good, tested this while running targets and working as expected

**Pull request merged**
