### PR TITLE
29 Make new cij_delay variable

### LINKED ISSUE #29: Make new cij_delay variable
Variable to indicate if the stay (`cij_marker`) has a delay episode or episodes associated with it.

### PR DESCRIPTION
**Pull request by Moohan**
This is probably not the most efficient way as we're already doing a CIJ level aggregate in `C01` for the `CIJ_PPA` variable. Ideally we'd do this and that together but that would require a new script and re-labelling all the scripts etc.

Assuming you don't spot any issues I think this is fine for now since we'll move everything to R at some point anyway!

Closes #29

### CODE REVIEW

**Comment by Moohan** [comment]
@Jennit07 If you manage to get the PPA stuff done (#49) I might piggyback off that code to also include a CIJ_delay count in the indiv file.

**Comment by Moohan** [comment]
@Jennit07 to add some lines to the individual file to create a count of delayed stays in the year.

**Comment by Jennit07** [comment]
As discussed, count for cij_delay added. Will have merge conflicts with ppa count as this was added on same line 75. Still needs copied across all years once confirmed :)

**Comment by Moohan** [comment]
I think this is good to go. Can you merge if you're happy with it too please?

**Review by Jennit07 — APPROVED** [review]
New cij_delay variable added to episode file, checked over, added a count for variable to individual file and test variables added to D05X. Ready to merge changes into Sep21 update branch

**Pull request merged**
