### PR TITLE
Add a single function to read files based on their extension

### PR DESCRIPTION
**Pull request by Moohan**
The idea here is that it will allow us to change the file type easily as the code will automatically read the data based on the file type.

### CODE REVIEW

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4482439863/attempts/1).



> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4491690655/attempts/1).

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4491690655/attempts/1).

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4494967105/attempts/1).

**Comment by Moohan** [comment]
Ready for review. I'll create a separate PR to implement this change.

**Review by Jennit07 — COMMENTED** [review]
I think this is looking good and i like the idea behind it! 

I've not had a chance to test this in R as i'm having problems installing the package `arrow`. This is the error below, any ideas why it won't install? seems to install it and then remove it? This is also on the old server at the moment due to Posit being locked up with targets running, will also need to try this on posit

```
> install.packages('arrow')
Installing package into ‘/home/jennit07/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/arrow_11.0.0.3.tar.gz'
Content type 'application/x-gzip' length 3921484 bytes (3.7 MB)
==================================================
downloaded 3.7 MB

* installing *source* package ‘arrow’ ...
** package ‘arrow’ successfully unpacked and MD5 sums checked
** using staged installation
------------------------- NOTE ---------------------------
Cannot install arrow: a C++17 compiler is required.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
ERROR: configuration failed for package ‘arrow’
* removing ‘/home/jennit07/R/x86_64-pc-linux-gnu-library/3.6/arrow’
Warning in install.packages :
  installation of package ‘arrow’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpjq4tBh/downloaded_packages’
```

**Comment by Moohan** [comment]
> I think this is looking good and i like the idea behind it! 
> 
> I've not had a chance to test this in R as i'm having problems installing the package `arrow`. This is the error below, any ideas why it won't install? seems to install it and then remove it? This is also on the old server at the moment due to Posit being locked up with targets running, will also need to try this on posit
> 
> ```
> > install.packages('arrow')
> Installing package into ‘/home/jennit07/R/x86_64-pc-linux-gnu-library/3.6’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/src/contrib/arrow_11.0.0.3.tar.gz'
> Content type 'application/x-gzip' length 3921484 bytes (3.7 MB)
> ==================================================
> downloaded 3.7 MB
> 
> * installing *source* package ‘arrow’ ...
> ** package ‘arrow’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ------------------------- NOTE ---------------------------
> Cannot install arrow: a C++17 compiler is required.
> See https://arrow.apache.org/docs/r/articles/install.html
> ---------------------------------------------------------
> ERROR: configuration failed for package ‘arrow’
> * removing ‘/home/jennit07/R/x86_64-pc-linux-gnu-library/3.6/arrow’
> Warning in install.packages :
>   installation of package ‘arrow’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/tmp/Rtmpjq4tBh/downloaded_packages’
> ```

Simple answer is you can't install it on the old server 😅 hopefully you managed to test the rest?

**Review by Jennit07 — APPROVED** [review]
Tested this function and it looks good! ready to approve/merge

**Pull request merged**
