### PR TITLE
Care Home all episodes

### LINKED ISSUE #487: All Care Home

### PR DESCRIPTION
**Pull request by Moohan**
~~I was working through this again and have addressed some issues but it's still not finished.~~

~~Feel free to review this and I'll make those changes, or suggest any fixes or improvements to the broken bits!~~

Now done and ready for review!

Closes #487

### CODE REVIEW

**Comment by Moohan** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4046769161/attempts/1).

**Review by lizihao-anu — APPROVED** [review]

**Comment by Jennit07** [comment]
Currently having a look through this and will leave any comments

**Review by Jennit07 — CHANGES_REQUESTED** [review]
Just two small comments from me. The code looks good and i tested this from start to finish on posit and there are no bugs to be found. I didnt have any issues with write speeds either from using this which is nice to know! I have compared the `rds` to `zsav` version and all the variables are looking good/matching! 

One thing to point out:

zsav version: 
193440 rows

rds version: 
203698 rows

I'm not sure if this difference is due to the code being processed at different stages now, i.e the ch name changes and death fixes. Would you agree this could be the reason or can you think of another explanation? Other than the comments i am happy with the code and happy to merge this

**Review by Jennit07 — APPROVED** [review]

**Comment by Jennit07** [comment]
Tested this through and ready to merge!

**Pull request merged**
