### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by SwiftySalmon**
remove some packages from description file that don't get used anywhere

### CODE REVIEW

**Review by Jennit07 — APPROVED** [review]
Looks good. Made one change to the authors in description

**Comment by Jennit07** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/10469297653/attempts/1).

@check-spelling-bot apply updates.

**Comment by Jennit07** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/10469690723/attempts/1).

@check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/10469690723/attempts/1).

**Comment by Moohan** [comment]
Hey, not sure why I've randomly received notifications about this PR :shrug:

I noticed you'd removed me and others from the DESCRIPTION - The usual practice is to have a single person as the 'package maintainer' they get the role `cre` (creator) - in the case of this package I put PHS as this which wouldn't be ok on CRAN but I think is fine...

For everyone else, small contributions would be 'contributor' `ctb` and bigger contributions should be 'authors' `aut`. People can have as many roles as required. 

See the [phsmethods DESCRIPTION](https://github.com/Public-Health-Scotland/phsmethods/blob/master/DESCRIPTION) and these docs - https://r-pkgs.org/description.html#sec-description-authors-at-r

**Pull request merged**
