### PR TITLE
934 review tests on createslf package

### PR DESCRIPTION
**Pull request by lizihao-anu**

### CODE REVIEW

**Comment by lizihao-anu** [comment]
> # @check-spelling-bot Report
> ### 🔴 Please review
> See the [📂 files](https://github.com/Public-Health-Scotland/source-linkage-files/pull/942/files/) view, the [📜action log](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8521649016/job/23340235114#step:4:1), or [📝 job summary](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8521649016/attempts/1#summary-23340235114) for details.
> 
> #### Unrecognized words (2)
> MONTHFLAG RDD
> 
> To accept these unrecognized words as correct, you could run the following commands
> **OR**
> 
> To have the bot accept them for you, reply quoting the following line: @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8521649016/attempts/1).
> 
> Available 📚 dictionaries could cover words (expected and unrecognized) not in the 📘 dictionary
> Errors (2)
> If the flagged items are 🤯 false positives

@check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8521649016/attempts/1).

**Comment by lizihao-anu** [comment]
Going to fix the "no visible binding" issues in this branch.

**Comment by lizihao-anu** [comment]
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541148819/attempts/1).

**Comment by lizihao-anu** [comment]
> # @check-spelling-bot Report
> ### 🔴 Please review
> See the [📂 files](https://github.com/Public-Health-Scotland/source-linkage-files/pull/942/files/) view, the [📜action log](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/job/23400163937#step:4:1), or [📝 job summary](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/attempts/1#summary-23400163937) for details.
> 
> #### Unrecognized words (2)
> MONTHFLAG RDD
> 
> To accept these unrecognized words as correct, you could run the following commands
> **OR**
> 
> To have the bot accept them for you, reply quoting the following line: @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/attempts/1).
> 
> Available 📚 dictionaries could cover words (expected and unrecognized) not in the 📘 dictionary
> Errors (2)
> If the flagged items are 🤯 false positives

@check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/attempts/1).

**Comment by lizihao-anu** [comment]
> # @check-spelling-bot Report
> ### 🔴 Please review
> See the [📂 files](https://github.com/Public-Health-Scotland/source-linkage-files/pull/942/files/) view, the [📜action log](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/job/23400163937#step:4:1), or [📝 job summary](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/attempts/1#summary-23400163937) for details.
> 
> #### Unrecognized words (2)
> MONTHFLAG RDD
> 
> To accept these unrecognized words as correct, you could run the following commands
> **OR**
> 
> To have the bot accept them for you, reply quoting the following line: @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/8541261628/attempts/1).
> 
> Available 📚 dictionaries could cover words (expected and unrecognized) not in the 📘 dictionary
> Errors (2)
> If the flagged items are 🤯 false positives

**Comment by lizihao-anu** [comment]
Finally, all checks have passed! all green!

**Review by Jennit07 — APPROVED** [review]
Looks good! Well done for resolving all of the queries :)

**Pull request merged**
