### PR TITLE
Bug - NSUs being assigned psychiatry in the service use cohort

### LINKED ISSUE #907: Bug- NSUs showing psychiatry in service use cohort
The source team have identified an issue where NSUs have a large number of records coded as psychiatry compared to previous outputs. I checked the code and could not spot any obvious issues with the logic so something weird is happening with NSUs. This should be coded as unassigned or other as a NSU should not be classed in the service use cohort since they have not had any activity.

### PR DESCRIPTION
**Pull request by Jennit07**
Due to a coding error, the `dplyr::pick` was not working correctly when trying to take the average for assigning the label `unassigned`. This was causing NSUs to have the label `psychiatry` attached as this was the next name available. The fix is to specify all of the columns needed to take an average for assigning the label `unassigned`. This has a big impact on the figures. 

The  current 'live' files:

```
  service_use_cohort       n
   <chr>                <int>
 1 Elective Inpatient  488510
 2 Geriatric           293863
 3 Limited Daycases    725538
 4 Maternity           206488
 5 Multiple Emergency 1140659
 6 Outpatients        1102837
 7 Prescribing        3982957
 **8 Psychiatry         1601193**
 9 Routine Daycase     178739
10 Single Emergency   1116014
**11 Unassigned          250917**
12 Unscheduled Care   1718283
13 NA                   55697

```

after the fix: 

```
   service_use_cohort       n
   <chr>                <int>
 1 Elective Inpatient  488521
 2 Geriatric           293869
 3 Limited Daycases    725583
 4 Maternity           206488
 5 Multiple Emergency 1140688
 6 Outpatients        1102878
 7 Prescribing        3982958
 **8 Psychiatry          111859**
 9 Routine Daycase     178742
10 Single Emergency   1116042
**11 Unassigned         1740237**
12 Unscheduled Care   1718269
13 NA                   55180
```

Ive asked the source team if they can run through a test to see the impact on their figures so i am opening this as a draft for now incase further changes are needed. 

closes #907

### CODE REVIEW

**Review by SwiftySalmon — DISMISSED** [review]
Looks good to me! Good work finding the issue! Can merge once Aiden has given feedback

**Comment by Jennit07** [comment]
Update: I have sent a test individual file to the source team to test with these changes. Will update again when we have some feedback

**Comment by Jennit07** [comment]
Update: Source team are happy with the test file i sent and it has made a big impact on the figures/more in line with what they would expect. Ready for review/merge

**Review by SwiftySalmon — APPROVED** [review]
looks good and source team are happy so ready to merge

**Pull request merged**
