### PR TITLE
Source Extract fn

### PR DESCRIPTION
**Pull request by catherineholland1**
quick one

edit to `get_source_extract_function` to allow for file extension to be changed

### CODE REVIEW

**Review by Moohan — CHANGES_REQUESTED** [review]
The extension parameter needs documenting.

Apart from that, an alternative way to do this might be to use the existing `get_file_path` function?

```r
get_source_extract_path <- function(year,
                                    type = c("Acute", "Mental", "DD", "Client"),
                                    ext = c("csv", "sav", "zsav", "rds")) {
  file_name <- dplyr::case_when(
    type == "Acute" ~ "acute_for_source",
    type == "Mental" ~ "mental_health_for_source",
    type == "DD" ~ "DD_for_source",
    type == "Client" ~ "Client_for_Source"
  )

  source_extract_path <- get_file_path(
    directory = fs::path("/conf/sourcedev/Source_Linkage_File_Updates", year),
    file_name = glue::glue("{file_name}-20{year}"),
    ext = ext,
    check_mode = "write"
  )

  return(source_extract_path)
}
```

**Comment by catherineholland1** [comment]
> The extension parameter needs documenting.
> 
> Apart from that, an alternative way to do this might be to use the existing `get_file_path` function?
> 
> ```r
> get_source_extract_path <- function(year,
>                                     type = c("Acute", "Mental", "DD", "Client"),
>                                     ext = c("csv", "sav", "zsav", "rds")) {
>   file_name <- dplyr::case_when(
>     type == "Acute" ~ "acute_for_source",
>     type == "Mental" ~ "mental_health_for_source",
>     type == "DD" ~ "DD_for_source",
>     type == "Client" ~ "Client_for_Source"
>   )
> 
>   source_extract_path <- get_file_path(
>     directory = fs::path("/conf/sourcedev/Source_Linkage_File_Updates", year),
>     file_name = glue::glue("{file_name}-20{year}"),
>     ext = ext,
>     check_mode = "write"
>   )
> 
>   return(source_extract_path)
> }
> ```

Whatever may be better/more efficient? Just adapted this one Jen made to keep it in line with the get_extract_path ?

**Review by Moohan — DISMISSED** [review]
I just made and pushed some changes, so I'm happy. I'll pass it to Jen to check and merge though.

**Review by Jennit07 — APPROVED** [review]
Looks good - I've added Maternity to the list for the boxi extract function. Ready to merge

**Review by Moohan — APPROVED** [review]

**Pull request merged**
